version: "3.7"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: ddot-mps-authentication-api
    container_name: ddot-mps-authentication-api-container
    ports:
      - "3300:8080"


volumes:
  web-root:
    driver: local